### ISSUE TITLE
PCIE doesn't work

### ISSUE THREAD

**Issue by bkeys** [MarvellEmbeddedProcessors/edk2-open-platform#2] opened 2018-03-12 02:19 UTC
I followed these instructions
http://wiki.macchiatobin.net/tiki-index.php?page=Build+from+source+-+UEFI+EDK+II&highlight=edk
And with your `marvell-armada-wip` branch it indeed fixes the issue with the CPU being underclocked, but now my PCI-E port doesn't post. I see that there are some branches that mention PCI-E. Do you have any suggestions on how I can get my CPU to not be underclocked while also having my PCI-E port also POST so I can use my graphics card?

**Comment by wojtas-marcin** [comment] 2018-03-12 06:42
Hi,

In fact, the CPU wasn't underclocked - it was only a faulty printout, fixed in recent patches. From top of marvell-armada-wip you can already use GPU (I use it with Debian https://d-i.debian.org/daily-images/arm64/daily/netboot/mini.iso).

Patches for PCIE support in UEFI will be ready in coming days and pushed, but since there are no GPU drivers in UEFI for ARM, they should be irrelevant for the above.

**Comment by bkeys** [comment] 2018-03-12 15:17
I am pretty sure that it's underclocked because when I run
`dmidecode | grep "Current Speed"`
It will tell me that it's only running at 1300mhz

**Comment by wojtas-marcin** [comment] 2018-03-12 15:20
Hi dmidecode reads SMBIOS table, which had a value hardcoded to 1300MHz, not the actual HW settings. Regardless the print, your device worked in the speed as set on the jumpers.

Anyway, the patch:
https://github.com/MarvellEmbeddedProcessors/edk2-open-platform/commit/de727c54258be3d80109f950e2a138ba29e777f8

Enabled reading and printing the actual speed, so it's no longer an issue.

Thanks,
Marcin

**Comment by bkeys** [comment] 2018-03-12 15:39
Alright well, is there a way to get a notification when the PCI-E support will be available?

**Comment by wojtas-marcin** [comment] 2018-03-12 15:47
Of course, I'll update about it.

Out of curiosity - what do you need PCIE support inside uefi for? Are you willing to boot with ACPI?

For booting with DT (e.g. debian, ubuntu), everything needed is in place already on marvell-armada-wip.

**Comment by bkeys** [comment] 2018-03-12 15:51
I don't care what I boot with so long as it works, but with the most current build you have on the marvell-armada-wip branch, Fedora says stuff about either the GPU or PCI-E failing to POST and then the boot hands. That does not happen with the older version of the firmware I am running right now

**Comment by wojtas-marcin** [comment] 2018-03-12 16:48
1. What kind GPU model are you using?

2. Can you share your board revision number?

**Comment by bkeys** [comment] 2018-03-12 17:38
Sure
I have a AMD 6450 (AMD CAICOS)
I have the 1.3 revision of the board.

**Comment by wojtas-marcin** [comment] 2018-03-13 14:59
Thanks. Can you please:
- build clean a branch with yesterday's device tree update (https://github.com/MarvellEmbeddedProcessors/edk2-open-platform/commit/b316449f24fdac9fc14c87d23f4680dfd789c7b8)
- let know, how it goes and provide with full boot log (from first lines after reset).

Best regards,
Marcin

**Comment by b-man** [comment] 2018-04-07 21:41
Hello,

I've recently acquired a Macchioatobin board and I was planning on getting a graphics card to use with it (likely [this one](https://www.amazon.com/GeForce-GDDR5-Graphics-Graphic-GT710-SL-2GD5-CSM/dp/B073GF2CL6) as it is also being used for the SynQuacer 24-core Developer Box).

I understand that there are a couple of branches on this repository focusing on PCIe enablement, and I'm curious to know, how far along are those branches in enabling support?

By having PCIe support in the UEFI, we could have the ability to interact with the UEFI and other pre-boot environments (like grub) without the need to use a serial cable when a graphics card is attached.
It would also make certain Linux distributions easier to install as not all installers provide a text-based interface over serial without modifications.

Once I get my graphics card, I would love to help out in testing PCIe support in the UEFI.

**Comment by wojtas-marcin** [comment] 2018-04-07 22:23
Hi Brian,

Recently we've reworked the PCIE patches, I will push it to marvell-armada-wip right after the weekend. I'll also clean the repo from outdated branches, so that there is no confusion in future.

Thanks,
Marcin

**Comment by b-man** [comment] 2018-04-27 00:39
Hello Marcin,

I've finally got a graphics card for my Macchiatobin, an ASUS Radeon R7 240, and I can report that it is detected by the UEFI, but nothing comes up on the monitor. Here is a dump of the PCI info from UEFI:

>   Seg  Bus  Dev  Func
>    ---  ---  ---  ----
>     00   00   00    00 ==> Display Controller - VGA/8514 controller
>              Vendor 1002 Device 6613 Prog Interface 0
>     00   00   00    01 ==> Multimedia Device - Mixed mode device
>              Vendor 1002 Device AAB0 Prog Interface 0


Here is a more detailed dump:

> Vendor ID(0): 1002     Device ID(2): 6613
> Command(4): 0000
>   (00)I/O space access enabled:       0  (01)Memory space access enabled:    0
>   (02)Behave as bus master:           0  (03)Monitor special cycle enabled:  0
>   (04)Mem Write & Invalidate enabled: 0  (05)Palette snooping is enabled:    0
>   (06)Assert PERR# when parity error: 0  (07)Do address/data stepping:       0
>   (08)SERR# driver enabled:           0  (09)Fast back-to-back transact...:  0
> 
> Status(6): 0010
>   (04)New Capabilities linked list:   1  (05)66MHz Capable:                  0
>   (07)Fast Back-to-Back Capable:      0  (08)Master Data Parity Error:       0
>   (09)DEVSEL timing:               Fast  (11)Signaled Target Abort:          0
>   (12)Received Target Abort:          0  (13)Received Master Abort:          0
>   (14)Signaled System Error:          0  (15)Detected Parity Error:          0
> 
> Revision ID(8): 00 BIST(0F):  Incapable
> Cache Line Size(C): 00                 Latency Timer(D): 00
> Header Type(0E):    80, Multi-function, PCI device
> Class: Display Controller - VGA/8514 controller - VGA compatible
> 
> Pci Express device capability structure:
> CapID( 0):          10            NextCap Ptr( 1):    A0
> Cap Register( 2):             0012
>   Capability Version(3:0):          0x0002
>   Device/PortType(7:4):             Legacy PCI Express Endpoint
>   Interrupt Message Number(13:9):   0x00000
> Device Capabilities( 4):      00008FA1
>   Max_Payload_Size Supported(2:0):          256 bytes
>   Phantom Functions Supported(4:3):         0
>   Extended Tag Field Supported(5):          8-bit Tag field supported
>   Endpoint L0s Acceptable Latency(8:6):     Maximum of 8 us
>   Endpoint L1 Acceptable Latency(11:9):     No limit
>   Role-based Error Reporting(15):           1
>   Function Level Reset Capability(28):      0
> Device Control( 8):           2810
>   Correctable Error Reporting Enable(0):    0
>   Non-Fatal Error Reporting Enable(1):      0
>   Fatal Error Reporting Enable(2):          0
>   Unsupported Request Reporting Enable(3):  0
>   Enable Relaxed Ordering(4):               1
>   Max_Payload_Size(7:5):                    128 bytes
>   Extended Tag Field Enable(8):             0
>   Phantom Functions Enable(9):              0
>   Auxiliary (AUX) Power PM Enable(10):      0
>   Enable No Snoop(11):                      1
>   Max_Read_Request_Size(14:12):             512 bytes
> Device Status( A):            0009
>   Correctable Error Detected(0):            1
>   Non-Fatal Error Detected(1):              0
>   Fatal Error Detected(2):                  0
>   Unsupported Request Detected(3):          1
>   AUX Power Detected(4):                    0
>   Transactions Pending(5):                  0
> Link Capabilities( C):        04400C83
>   Maximum Link Speed(3:0):                            8.0 GT/s
>   Maximum Link Width(9:4):                            x8
>   Active State Power Management Support(11:10):       L0s and L1 Supported
>   L0s Exit Latency(14:12):                            Less than 64ns
>   L1 Exit Latency(17:15):                             Less than 1us
>   Clock Power Management(18):                         0
>   Surprise Down Error Reporting Capable(19):          0
>   Data Link Layer Link Active Reporting Capable(20):  0
>   Link Bandwidth Notification Capability(21):         0
>   Port Number(31:24):                                 0x04
> Link Control(10):             0000
>   Active State Power Management Control(1:0):         Disabled
>   Read Completion Boundary (RCB)(3):                  64 byte
>   Common Clock Configuration(6):                      0
>   Extended Synch(7):                                  0
>   Enable Clock Power Management(8):                   0
>   Hardware Autonomous Width Disable(9):               0
>   Link Bandwidth Management Interrupt Enable(10):     0
>   Link Autonomous Bandwidth Interrupt Enable(11):     0
> Link Status(12):              1043
>   Current Link Speed(3:0):                            8.0 GT/s
>   Negotiated Link Width(9:4):                         x4
>   Link Training(11):                                  0
>   Slot Clock Configuration(12):                       1
>   Data Link Layer Link Active(13):                    0
>   Link Bandwidth Management Status(14):               0
>   Link Autonomous Bandwidth Status(15):               0
> Slot Capabilities(14):        00000000
> Slot Control(18):             0000
> Slot Status(1A):              0000
> Root Control(1C):             0000
> Root Capabilities(1E):        0000
> Root Status(20):              00000000
>   VendorSpecific
>     VendorSpecificHeader           1010001
>     00000100: 0B 00 01 15 01 00 01 01-00 00 00 00 00 00 00 00  *................
> *
>   Advanced Error Reporting
>     UncorrectableErrorStatus       00000000
>     UncorrectableErrorMask         00000000
>     UncorrectableErrorSeverity     00462030
>     CorrectableErrorStatus         00003000
>     CorrectableErrorMask           00002000
>     AdvancedErrorCapAndControl     000000A0
>     HeaderLog1                     00000000
>     HeaderLog2                     00000000
>     HeaderLog3                     00000000
>     HeaderLog4                     00000000
>     RootErrorCommand               00000000
>     RootErrorStatus                00000000
>     ErrorSourceIdentification      0000
>     CorrectableErrorSourceIden     0000
>     TlpPrefixLog1                  00000000
>     TlpPrefixLog2                  00000000
>     TlpPrefixLog3                  00000000
>     TlpPrefixLog4                  00000000
>     00000150: 01 00 02 20 00 00 00 00-00 00 00 00 30 20 46 00  *... ........0 F.
> *
>     00000160: 00 30 00 00 00 20 00 00-A0 00 00 00 00 00 00 00  *.0... ..........
> *
>     00000170: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  *................
> *
>     00000180: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  *................
> *
>     00000190: 00 00 00 00 00 00 00 00-                         *........*
>   Resizeable Bar Capability [1]
>     ResizableBarCapability         0001F000
>     ResizableBarControl            0820
>     00000200: 15 00 01 27 00 F0 01 00-                         *...'....*
>   Secondary PCI Express Extended Capability
>     LinkControl3                   00000000
>     LaneErrorStatus                00000000
>     EqualizationControl:
>         0000027C: 00 70 00 70 00 70 00 70-00 00 00 00 00 00 00 00  *.p.p.p.p....
> ....*
>     00000270: 19 00 01 00 00 00 00 00-00 00 00 00 00 70 00 70  *.............p.p
> *
>     00000280: 00 70 00 70 00 00 00 00-00 00 00 00              *.p.p........*
> 

I've also made a dump of the PCI information detected from openSUSE Tumbleweed:

> linux-of0k:~ # lspci -v
> 00:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Oland PRO [Radeon R7 240/340] (prog-if 00 [VGA controller])
>         Subsystem: ASUSTeK Computer Inc. Device 048b
>         Flags: fast devsel, IRQ 31
>         Memory at 800000000 (64-bit, prefetchable) [size=256M]
>         Memory at 810000000 (64-bit, non-prefetchable) [size=256K]
>         I/O ports at 1000 [size=256]
>         Expansion ROM at c0000000 [disabled] [size=128K]
>         Capabilities: [48] Vendor Specific Information: Len=08 <?>
>         Capabilities: [50] Power Management version 3
>         Capabilities: [58] Express Legacy Endpoint, MSI 00
>         Capabilities: [a0] MSI: Enable- Count=1/1 Maskable- 64bit+
>         Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
>         Capabilities: [150] Advanced Error Reporting
>         Capabilities: [200] #15
>         Capabilities: [270] #19
>         Kernel driver in use: radeon
>         Kernel modules: radeon
> 
> 00:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Cape Verde/Pitcairn HDMI Audio [Radeon HD 7700/7800 Series]
>         Subsystem: ASUSTeK Computer Inc. Device aab0
>         Flags: bus master, fast devsel, latency 0, IRQ 32
>         Memory at 810040000 (64-bit, non-prefetchable) [size=16K]
>         Capabilities: [48] Vendor Specific Information: Len=08 <?>
>         Capabilities: [50] Power Management version 3
>         Capabilities: [58] Express Legacy Endpoint, MSI 00
>         Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
>         Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
>         Capabilities: [150] Advanced Error Reporting
>         Kernel driver in use: snd_hda_intel
>         Kernel modules: snd_hda_intel
> 
> linux-of0k:~ #

I've also made a [log detailing the entire boot process from reset](https://ghostbin.com/paste/wfxma). I needed to boot with ACPI enabled as the kernel would hang at PCI discovery if I didn't.

**Comment by b-man** [comment] 2018-04-28 06:45
@semihalf-wojtas-marcin 

I'm not sure if you've looked into this or not, but it appears that we may need to
use [X86EmulatorPkg](https://github.com/ardbiesheuvel/X86EmulatorPkg) to properly initialize graphics cards/other cards that use option ROMs in UEFI on this platform, as [detailed in this article](https://www.suse.com/c/revolutionizing-arm-technology-x86_64-option-rom-aarch64/).

**Comment by b-man** [comment] 2018-04-29 00:59
Good news!

I was able to get my graphics card working in UEFI using the above method, and I can now
see the Tianocore boot progress screen, UEFI menu, and grub menu on my monitor!

Boot screen: https://imgur.com/a/rhwPOpM
UEFI Menu: https://imgur.com/a/kNGB1E9

Linux detecting the framebuffer from UEFI:
```
[    1.375380] efifb: probing for efifb
[    1.375419] efifb: framebuffer at 0x800000000, using 1952k, total 1950k
[    1.375422] efifb: mode is 800x600x32, linelength=3328, pages=1
[    1.375425] efifb: scrolling: redraw
[    1.375425] efifb: scrolling: redraw
[    1.375428] efifb: Truecolor: size=8:8:8:8, shift=24:16:8:0
[    1.377390] Console: switching to colour frame buffer device 100x37
[    1.379146] fb0: EFI VGA frame buffer device
```

The only issues I'm facing now are a blank screen with an occasion non-blinking cursor
after the kernel start booting up (which may be more related to my Ubuntu installation),
and the radeon driver crashing when calling drm_pcie_get_speed_cap_mask().

Here is the backtrace of the radeon driver crash:

```
[    3.931020] [drm] Internal thermal controller with fan control
[    3.937025] Internal error: Accessing user space memory outside uaccess.h routines: 96000004 [#1] SMP
[    3.946283] Modules linked in: uas usb_storage aes_ce_blk aes_ce_cipher crc32_ce crct10dif_ce ghash_ce sha2_ce radeon(+) i2c_algo_bit sha256_arm64 sha1_ce ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops drm ahci_platform libahci_platform libahci xhci_plat_hcd aes_neon_bs aes_neon_blk crypto_simd cryptd aes_arm64
[    3.975554] CPU: 0 PID: 179 Comm: systemd-udevd Not tainted 4.15.0-20-generic #21-Ubuntu
[    3.983677] Hardware name: Marvell Armada 8040 MacchiatoBin/Armada 8040 MacchiatoBin, BIOS EDK II Apr 28 2018
[    3.993632] pstate: a0400005 (NzCv daif +PAN -UAO)
[    3.998510] pc : drm_pcie_get_speed_cap_mask+0x50/0x138 [drm]
[    4.004441] lr : si_dpm_init+0x64/0x13e8 [radeon]
[    4.009164] sp : ffff00000a2db690
[    4.012491] x29: ffff00000a2db690 x28: ffffdd2922b70000
[    4.017826] x27: ffff04d223fd0d50 x26: 0000000000000000
[    4.023162] x25: 000000ffffffffff x24: ffffdd292cc640a0
[    4.028495] x23: ffffdd2922e78800 x22: ffffdd2922b72000
[    4.033829] x21: 0000000000000000 x20: ffff00000a2db790
[    4.039164] x19: ffff1dd0a2188c08 x18: ffffffffffffffff
[    4.044497] x17: 0000000000000000 x16: ffff1dd0a0eff0b8
[    4.049832] x15: ffff1dd0a2188c08 x14: 42555300306e6f6d
[    4.055166] x13: 0000000000000040 x12: 0000000000000228
[    4.060501] x11: 0000000000000008 x10: ffff7f74a4860620
[    4.065835] x9 : ffff7f74a485ee00 x8 : ffffdd292e03b000
[    4.071169] x7 : 0000000000000000 x6 : 0000bf589e20a000
[    4.076504] x5 : ffff00000a2db3a0 x4 : 000000000000fffd
[    4.081838] x3 : 0000000000001106 x2 : 0000000000001166
[    4.087173] x1 : ffffdd292ccb8000 x0 : 00000000ffffffea
[    4.092508] Process systemd-udevd (pid: 179, stack limit = 0x00000000ba94a9e4)
[    4.099759] Call trace:
[    4.102279]  drm_pcie_get_speed_cap_mask+0x50/0x138 [drm]
[    4.107856]  si_dpm_init+0x64/0x13e8 [radeon]
[    4.112392]  radeon_pm_init+0x4c4/0x708 [radeon]
[    4.117189]  si_init+0x21c/0x4e0 [radeon]
[    4.121366]  radeon_device_init+0x514/0xc60 [radeon]
[    4.126500]  radeon_driver_load_kms+0xac/0x250 [radeon]
[    4.131810]  drm_dev_register+0x158/0x1f8 [drm]
[    4.136421]  drm_get_pci_dev+0x94/0x170 [drm]
[    4.140945]  radeon_pci_probe+0x8c/0xc8 [radeon]
[    4.145588]  local_pci_probe+0x44/0xa8
[    4.149353]  pci_device_probe+0x158/0x1c0
[    4.153380]  driver_probe_device+0x31c/0x470
[    4.157667]  __driver_attach+0xdc/0x128
[    4.161518]  bus_for_each_dev+0x78/0xd8
[    4.165369]  driver_attach+0x30/0x40
[    4.168958]  bus_add_driver+0x210/0x2a8
[    4.172809]  driver_register+0x6c/0x110
[    4.176661]  __pci_register_driver+0x58/0x68
[    4.181097]  radeon_init+0x70/0xd8 [radeon]
[    4.185299]  do_one_initcall+0x58/0x160
[    4.189151]  do_init_module+0x64/0x1d8
[    4.192915]  load_module+0x135c/0x15c8
[    4.196678]  SyS_finit_module+0x100/0x118
[    4.200703]  el0_svc_naked+0x30/0x34
[    4.204296] Code: 528220c3 52822cc2 128002a0 f9401c35 (79407aa1)
[    4.210415] ---[ end trace 7287a1a3e825cc6d ]---
```
I'm suspecting that this may be related to the above crash:

`[    0.037385] acpi PNP0A08:00: [Firmware Bug]: ECAM area [mem 0xe0008000-0xe0107fff] not reserved in ACPI namespace`

**UPDATE:**
I was able to work around this issue by disabling DPM for this card, but it appears that the cause of the crash was the result of attempting to read data from the ECAM area. Could the current method of shifting the PCIE base address by 32KB to work around the ghosting problem be causing the crash due to reading from an invalid address?

**Comment by b-man** [comment] 2018-04-29 06:04
I've been doing some more research on the ECAM issue mentioned in [this commit](https://github.com/MarvellEmbeddedProcessors/edk2-open-platform/commit/dedc13db83f4d1d91a0580bae5b9901eb41487dc) and the apparent use of [this device tree configuration](https://www.kernel.org/doc/Documentation/devicetree/bindings/pci/designware-pcie-ecam.txt) to work with this workaround, and I noticed that the SoC used in the Socionext Developer Box appears to use the same Synopsys IP that this SoC uses. It appears that they've been able to work around this issue by utilizing a stage 2 translation table hack at both the [arm-trusted firmware level](https://git.linaro.org/leg/noupstream/arm-trusted-firmware.git/commit/?h=synquacer&id=0541b9edd636bd45f80026218b65fe7644e86b47) and at the [UEFI level](https://git.linaro.org/leg/noupstream/edk2-platforms.git/commit/?h=developer-box&id=8e55eaa4c69f28509f3e801cfdb1e8275a579ccf) and [tied it together with this](https://git.linaro.org/leg/noupstream/edk2-platforms.git/commit/?h=developer-box&id=9dd8190e49956e02dbeeda7c5d8e08e854283f9e).

My question is what is stopping us from doing something similar?

**Comment by wojtas-marcin** [comment] 2018-05-01 07:17
Hi,

@b-man thank you for your involvement.

1. I'm aware of the DT boot problems with the PCIE, I moved to ecam description before your bug report, but apparently it needs something more, as I couldn't detect the rootbridge and the device. Marvell v4.4 LSP is capable of reconfiguring to the non-ecam mode, but the mainline driver appears not to be that good. I will go back to it soon.
2. We are working on the removing the ECAM shift, but thanks for pointing the Synquacer method.

Thanks,
Marcin

**Comment by wojtas-marcin** [comment] 2018-05-02 18:13
@b-man 
Please fetch updated https://github.com/MarvellEmbeddedProcessors/edk2-open-platform/commits/marvell-armada-wip

Two new commits:
https://github.com/MarvellEmbeddedProcessors/edk2-open-platform/commit/3c9e93fe527c5db043eb84aa72b5bdfb7b58275b
https://github.com/MarvellEmbeddedProcessors/edk2-open-platform/commit/aef549b4d49f6e2bd1891f89c8250a5f20c44ca8

Tested with GT630 graphic card with DT and ACPI. BTW, how did you disable the cards DRM?

Thanks,
Marcin

**Comment by b-man** [comment] 2018-05-02 23:00
@semihalf-wojtas-marcin 

I've tested those changes in both DT and ACPI mode and I can confirm that those
changes fixed the boot hang problem, thanks!

As for DRM, that wasn't what was disabled. What I disabled was DPM (Dynamic Power Management)
support for the graphics card, as it needed to probe for pcie speed information from the ECAM area
to work.

**Closed as completed** 2018-05-02 23:26 UTC
